In [1]:
from src.recommenders.content_based import ContentBasedRecommender

model = ContentBasedRecommender()

model.fit()

model.recommend_similar(
    movie_id=50,
    top_k=10
)

      movie_id                                   title  similarity_score
513        514                       Annie Hall (1977)          0.315782
666        667                      Audrey Rose (1977)          0.311677
1090      1091                    Pete's Dragon (1977)          0.305894
1292      1293                         Star Kid (1997)          0.303613
123        124                        Lone Star (1996)          0.277495
1060      1061                Evening Star, The (1996)          0.277495
1264      1265                        Star Maps (1997)          0.275645
221        222         Star Trek: First Contact (1996)          0.240872
379        380           Star Trek: Generations (1994)          0.234421
449        450  Star Trek V: The Final Frontier (1989)          0.191038

In [2]:
model.movies[
    model.movies["title"]
    .str.contains(
        "Toy Story",
        case=False
    )
]

,movie_id,title,release_date,video_release_date,imdb_url
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...

In [3]:
model.recommend_similar(
    movie_id=1,
    top_k=10
)

,movie_id,title,similarity_score
1071,1072,"Pyromaniac's Love Story, A (1995)",0.392081
1343,1344,"Story of Xinghua, The (1993)",0.357255
477,478,"Philadelphia Story, The (1940)",0.328801
547,548,"NeverEnding Story III, The (1994)",0.308313
307,308,FairyTale: A True Story (1997),0.303747
1052,1053,Now and Then (1995),0.265435
1546,1547,"Show, The (1995)",0.265435
1589,1590,"To Have, or Not (1995)",0.265435
1652,1653,Entertaining Angels: The Dorothy Day Story (1996),0.242928
598,599,Police Story 4: Project S (Chao ji ji hua) (1993),0.163685